version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    environment:
      - FE_URL=http://localhost:4173
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8002:8080"
    depends_on:
      - redis

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - be
