name: BE Lint and Test

on:
  push:
    branches:
      - main
    paths:
      - 'be/**'
  pull_request:
    branches:
      - main
    paths:
      - 'be/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install -r requirements.dev -r requirements.txt --system
        working-directory: be

      - name: Run Linter
        if: matrix.job == 'lint'
        run: ruff check .
        working-directory: be

      - name: Run Tests
        if: matrix.job == 'test'
        run: pytest
        working-directory: be